### ISSUE TITLE
looks great!

### ISSUE THREAD

**Issue by zartan9** [LyndonFan/NonogramMaker#1]
is there a gui for noncoder window user like me? Is this available for commercial use? thank you.

**Comment by LyndonFan** [comment]
Thanks for the praise! There isn't a GUI version at the moment, but I'm more than happy to figure something out.
I'm happy for this to be for commercial use as long as you visibly credit me and this project.

**Comment by zartan9** [comment]
that would be great! yes keep me posted thank you!
